function [fitresult, gof] = createFit(x1, y1, z1)
%CREATEFIT(X1,Y1,Z1)
%  Create a fit.
%
%  Data for 'Linear Interp' fit:
%      X Input : x1
%      Y Input : y1
%      Z Output: z1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Mar-2017 15:01:01


%% Fit: 'Linear Interp'.
[xData, yData, zData] = prepareSurfaceData( x1, y1, z1 );

% Set up fittype and options.
ft = 'linearinterp';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
% figure( 'Name', 'Linear Interp' );
% h = plot( fitresult, [xData, yData], zData );
% legend( h, 'Linear Interp', 'z1 vs. x1, y1', 'Location', 'NorthEast' );
% % Label axes
% xlabel x1
% ylabel y1
% zlabel z1
% grid on
view( -73.3, 59.3 );


